language: node_js
node_js:
  - "stable"

services:
  - mongodb

script:
  - "npm install -g codecov"
  - "npm run client-test"
  - "npm run server-test"

after_script: "cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

after_success:
 - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
