language: node_js
node_js:
  - "stable"

services:
  - mongodb

script:
  - "npm run server-test"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

after_success:
 - "npm run coverage"
