language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
script:
  - "npm run client-test"
  - "npm run server-test"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
